# Generated by Django 3.2.3 on 2021-07-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='NORMAL', max_length=10),
        ),
    ]
